# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.7.9"

env:
  - PIP_USE_MIRRORS=true

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - python setup.py build

script: make coverage-no-open

after_success:
  coveralls
